name: Fuzu Job Scraper

on:
  schedule:
    - cron: "0 7 * * *"  # Runs daily at 7:00 AM UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  scrape-and-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install selenium
        pip install beautifulsoup4
        pip install yagmail

    - name: Run scraper
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python fuzu_scraper.py